name: pipeline-application
kind: pipeline
type: docker

steps:
  - name: Compile And Package
    image: openjdk
    commands:
      - ./mvnw clean compile
      - ./mvnw package
  - name: Publish Image
    image: plugins/docker
    repo: karanamsridhar/spring-boot-pipeline
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
