name: pipeline-application
kind: pipeline
type: docker

steps:
  - name: Compile
    image: openjdk
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
    commands:
      - ./mvnw clean compile
  - name: Package
    image: openjdk
    commands:
      - ./mvnw package -Djib.to.auth.username=$USERNAME -Djib.to.auth.password=$PASSWORD -Djib.to.image=docker.io/karanamsridhar/spring-boot-pipeline:v3
