name: pipeline-application
kind: pipeline
type: docker

steps:
  - name: Compile And Package
    image: openjdk
    commands:
      - ./mvnw clean compile
      - ./mvnw package
  - name: Publish Image
    image: plugins/docker
    settings:
      repo: karanamsridhar/spring-boot-pipeline
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: latest
